### ISSUE TITLE
一个小小的疑问

### ISSUE THREAD

**Issue by Riajyuu** [Greedysky/greedysky.github.io#1]
贵站似乎是基于hexo的主题，BGM是如何实现的，我以为那是需要后端的

**Comment by Greedysky** [comment]
不需要后端， 就是个静态页面。

**Comment by Riajyuu** [comment]
那么这是特定主题的功能吗？还是hexo就能做到，如果hexo就能做到求教具体实现，因为在hexo文档中没有看到相关内容。

**Comment by Greedysky** [comment]
这不是hexo的相关内容 是自己定制的页面，通过页面跳转。自己定义的页面在Home目录下可以看到。

**Comment by Riajyuu** [comment]
明白了。thx
